package cc.design7.pl9m.parse;

import cc.design7.pl9m.syntax.SourceLocation;
import org.jetbrains.annotations.Nullable;

public record Token(Kind kind, SourceLocation location, @Nullable Object value) {
    public enum Kind {
        IDENT,
        LIT_INT,
        LIT_FLOAT,
        LIT_STRING,

        KW_TRUE,
        KW_FALSE,
        KW_LET,
        KW_REC,
        KW_IN,
        KW_NATIVE,
        KW_DECL,
        KW_TYPE,
        KW_BEGIN,
        KW_IF,
        KW_THEN,
        KW_ELSE,
        KW_LOOP,
        KW_BREAK,
        KW_CONTINUE,
        KW_MATCH,
        KW_CASE,
        KW_DEFAULT,
        KW_RETURN,
        KW_LAMBDA,
        KW_FN,
        KW_END,
        KW_INT,
        KW_FLOAT,
        KW_BOOL,
        KW_STRING,

        SYM_EQ,
        SYM_DCOLON,
        SYM_LPAREN,
        SYM_RPAREN,
        SYM_ARROW,
        SYM_PIPE,
        SYM_COMMA,
        SYM_LT,
        SYM_GT,
        SYM_LE,
        SYM_GE,
        SYM_F_LT,
        SYM_F_GT,
        SYM_F_LE,
        SYM_F_GE,
        SYM_DOT,
        SYM_LBRACKET,
        SYM_RBRACKET,
        SYM_PLUS,
        SYM_MINUS,
        SYM_TILDE,
        SYM_EXCLAIM,
        SYM_F_PLUS,
        SYM_F_MINUS,
        SYM_ASTER,
        SYM_SLASH,
        SYM_PERCENT,
        SYM_F_ASTER,
        SYM_F_SLASH,
        SYM_F_PERCENT,
        SYM_DLT,
        SYM_DGT,
        SYM_TGT,
        SYM_DEQ,
        SYM_NEQ,
        SYM_AMP,
        SYM_CARET,
        SYM_DAMP,
        SYM_DPIPE,
        SYM_COLONEQ
    }
}
