program ::= global-decl-list

global-decl-list ::= global-decl*

global-decl ::= let-decl | type-decl

let-decl ::= 'let' (let-normal-decl | let-native-decl)

let-normal-decl ::= 'rec'? let-assign-list

let-native-decl ::= 'native' identifier '=' string

type-decl ::= 'type' identifier '=' type-definition

type-definition ::= type-constructor-list
                  | 'native' string

type-constructor-list ::= type-constructor-list '|' type-constructor
                        | type-constructor

type-constructor ::= identifier identifier*

let-assign-list ::= let-assign+

let-assign ::= identifier '=' expr

expr ::= application-expr | non-application-expr

non-application-expr ::= integer
                       | float
                       | 'true' | 'false'
                       | string
                       | identifier
                       | abstraction-expr
                       | let-expr
                       | stmt-list
                       | return-expr
                       | break-expr
                       | continue-expr
                       | if-expr
                       | loop-expr
                       | '(' expr ')'

abstraction-expr ::= ('\\' | 'lambda') (identifier+ | '()') '.' expr

application-expr ::= non-application-expr+

let-expr ::= 'let' 'rec'? let-assign-list 'in' expr

stmt-list ::= 'begin' semicolon-sep-expr-list 'end'

return-expr ::= 'return' expr?

break-expr ::= 'break' expr?

continue-expr ::= 'continue'

if-expr ::= 'if' expr 'then' expr ('else' expr)?

loop-expr ::= 'loop' expr 'end'

semicolon-sep-expr-list ::= semicolon-sep-expr-list ';' expr | expr
